# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
      env:
        CI: true
    - run: yarn generate --fail-on-error
      env:
        CI: true
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.4.0
      env:
        GITHUB_PAT: ${{ secrets.GH_PAT }}
      with:
        # Git branch where assets will be deployed
        target_branch: gh-pages
        # Create incremental commit instead of doing push force
        keep_history: true
        # Allow an empty commit to be created
        allow_empty_commit: true
        # Build directory to deploy
        build_dir: dist
        # Commit author's name
        committer_name: Kamontat Chantrachirathumrong
        # Commit author's email
        committer_email: developer@kamontat.net
        # Commit message
        commit_message: updates new content
